"""LLM Client for code generation"""
import os
import json
import logging
from abc import ABC, abstractmethod
from typing import Optional, List, Dict, Any
from dataclasses import dataclass


logger = logging.getLogger(__name__)


@dataclass
class LLMResponse:
    content: str
    model: str
    usage: Dict[str, int]
    finish_reason: str


class LLMClient(ABC):
    """Abstract base class for LLM clients"""
    
    @abstractmethod
    def generate(self, prompt: str, **kwargs) -> LLMResponse:
        """Generate a response from the LLM"""
        pass
    
    @abstractmethod
    def is_available(self) -> bool:
        """Check if the LLM client is available"""
        pass


class OpenAIClient(LLMClient):
    """OpenAI GPT client"""
    
    def __init__(self, api_key: Optional[str] = None, model: str = "gpt-4"):
        self.api_key = api_key or os.environ.get("OPENAI_API_KEY")
        self.model = model
        self._client = None
    
    def _get_client(self):
        if self._client is None:
            try:
                from openai import OpenAI
                self._client = OpenAI(api_key=self.api_key)
            except ImportError:
                logger.warning("OpenAI package not installed")
                return None
        return self._client
    
    def is_available(self) -> bool:
        if not self.api_key:
            return False
        return self._get_client() is not None
    
    def generate(self, prompt: str, **kwargs) -> LLMResponse:
        client = self._get_client()
        if not client:
            raise RuntimeError("OpenAI client not available")
        
        response = client.chat.completions.create(
            model=kwargs.get("model", self.model),
            messages=[{"role": "user", "content": prompt}],
            temperature=kwargs.get("temperature", 0.7),
            max_tokens=kwargs.get("max_tokens", 4000),
        )
        
        return LLMResponse(
            content=response.choices[0].message.content,
            model=response.model,
            usage={
                "prompt_tokens": response.usage.prompt_tokens,
                "completion_tokens": response.usage.completion_tokens,
                "total_tokens": response.usage.total_tokens,
            },
            finish_reason=response.choices[0].finish_reason,
        )


class AnthropicClient(LLMClient):
    """Anthropic Claude client"""
    
    def __init__(self, api_key: Optional[str] = None, model: str = "claude-3-sonnet-20240229"):
        self.api_key = api_key or os.environ.get("ANTHROPIC_API_KEY")
        self.model = model
        self._client = None
    
    def _get_client(self):
        if self._client is None:
            try:
                from anthropic import Anthropic
                self._client = Anthropic(api_key=self.api_key)
            except ImportError:
                logger.warning("Anthropic package not installed")
                return None
        return self._client
    
    def is_available(self) -> bool:
        if not self.api_key:
            return False
        return self._get_client() is not None
    
    def generate(self, prompt: str, **kwargs) -> LLMResponse:
        client = self._get_client()
        if not client:
            raise RuntimeError("Anthropic client not available")
        
        response = client.messages.create(
            model=kwargs.get("model", self.model),
            max_tokens=kwargs.get("max_tokens", 4000),
            temperature=kwargs.get("temperature", 0.7),
            messages=[{"role": "user", "content": prompt}]
        )
        
        return LLMResponse(
            content=response.content[0].text,
            model=response.model,
            usage={
                "input_tokens": response.usage.input_tokens,
                "output_tokens": response.usage.output_tokens,
            },
            finish_reason=response.stop_reason,
        )


class MockLLMClient(LLMClient):
    """Mock LLM client for testing without API keys"""
    
    def __init__(self):
        pass
    
    def is_available(self) -> bool:
        return True
    
    def generate(self, prompt: str, **kwargs) -> LLMResponse:
        return LLMResponse(
            content="# Mock implementation generated by AI Coding Demo\n# This is a placeholder for actual LLM-generated code\n",
            model="mock",
            usage={"prompt_tokens": 100, "completion_tokens": 50, "total_tokens": 150},
            finish_reason="stop",
        )


def get_llm_client(provider: str = "openai", api_key: Optional[str] = None, model: str = "gpt-4") -> LLMClient:
    """Factory function to get LLM client"""
    clients = {
        "openai": OpenAIClient,
        "anthropic": AnthropicClient,
        "mock": MockLLMClient,
    }
    
    client_class = clients.get(provider.lower(), MockLLMClient)
    client = client_class(api_key=api_key, model=model)
    
    if not client.is_available() and provider != "mock":
        logger.warning(f"{provider} client not available, falling back to mock")
        return MockLLMClient()
    
    return client


def generate_code_prompt(
    issue_title: str,
    issue_body: str,
    file_path: str,
    file_content: str,
    language: str,
) -> str:
    """Generate a prompt for code implementation"""
    return f"""You are an expert software developer. Given the following GitHub issue and existing code file, implement the required changes.

## Issue Title
{issue_title}

## Issue Description
{issue_body}

## Target File
{file_path}

## Language
{language}

## Existing Code
```{language}
{file_content}
```

## Instructions
1. Analyze the issue and understand what needs to be implemented
2. Modify the existing code to address the issue
3. Only output the complete modified file content
4. Do not include explanations or markdown code blocks - output raw code only
5. Preserve the original code structure and style
"""


def generate_test_prompt(
    issue_title: str,
    issue_body: str,
    target_files: List[str],
    language: str,
) -> str:
    """Generate a prompt for test creation"""
    return f"""You are an expert software developer. Given the following GitHub issue, write appropriate unit tests.

## Issue Title
{issue_title}

## Issue Description
{issue_body}

## Target Files to Test
{chr(10).join(f"- {f}" for f in target_files)}

## Language
{language}

## Instructions
1. Analyze what functionality needs to be tested
2. Write comprehensive unit tests
3. Follow testing best practices for {language}
4. Only output the test code
5. Do not include explanations or markdown code blocks - output raw code only
"""
